[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "opt-level=z",
    "-C", "lto=fat",
    "-C", "codegen-units=1",
    "-C", "panic=abort",
    "-C", "strip=symbols",
]
